# Generated by Django 3.2.9 on 2021-11-06 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(max_length=50)),
                ('ordertype', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('custname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact', models.IntegerField()),
                ('ordertime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
