# Generated by Django 3.2.9 on 2021-11-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custname',
            new_name='cust_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordername',
            new_name='order_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordertime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordertype',
            new_name='order_type',
        ),
    ]
