# Generated by Django 3.2.9 on 2021-11-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0003_alter_order_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
    ]
