# Generated by Django 3.2.9 on 2021-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapi', '0004_remove_order_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=50)),
                ('contacted', models.BooleanField()),
            ],
        ),
    ]
